trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- script: echo "Iniciando sincronización de repositorios..."
  displayName: "Mensaje de inicio"

- script: |
    
    # Agregar Azure DevOps como remote (solo si no existe)
    git remote add azure https://acferreirar@dev.azure.com/acferreirar/Test/_git/TaskManagementTasks || true

    # Traer los últimos cambios de GitHub
    git fetch origin main
    git checkout main
    git merge origin/main --no-edit

    # Subir los cambios a Azure DevOps
    git push azure main
  displayName: "Sincronizar GitHub → Azure DevOps"