trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- script: echo "Iniciando sincronización de repositorios..."
  displayName: "Mensaje de inicio"

- script: |
    git config --global user.email "pipeline@azuredevops.com"
    git config --global user.name "Azure DevOps Pipeline"
    
    # Eliminar el remote si ya existe (evita duplicados)
    git remote remove azure || true

    # Agregar Azure DevOps como remote usando el PAT
    git remote add azure https://$(AZURE_DEVOPS_PAT)@dev.azure.com/TU_ORGANIZACION/TU_PROYECTO/_git/NOMBRE_DEL_REPO

    # Obtener cambios más recientes de GitHub
    git fetch origin main
    git checkout main
    git merge origin/main --no-edit

    # Enviar los cambios a Azure DevOps
    git push azure main
  displayName: "Sincronizar GitHub → Azure DevOps"